apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-4qub
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fcpk-tenant/quarkus/devfile-sample-code-with-quarkus-4qub@sha256:6eb12b11ade161ec429e3b12c094e42d7f708f9da49628a391754cd7096962b1
        name: my-java-quarkus
        resources: {}
status: {}
